# -*- coding: utf-8 -*-
"""Portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnAxYxhrpNhw6LQkEN0RBvUkR8XlcApF
"""

# 📦 Install libraries (run only once)
!pip install kiteconnect pandas



# 📌 Import modules
from kiteconnect import KiteConnect
import pandas as pd
import datetime
import os

# === Step 1: Authenticate ===
api_key = "l2b9rd6qe2tl8lu9"
api_secret = "kc1o2qgys5do8qhxijd906p5f6jbvp98"
kite = KiteConnect(api_key=api_key)

print("Login URL:", kite.login_url())  # Open in browser, login, get request_token
request_token = input("Enter request_token: ")
session = kite.generate_session(request_token, api_secret=api_secret)
kite.set_access_token(session["access_token"])

# 📊 Fetch Zerodha holdings
holdings = kite.holdings()
df = pd.DataFrame(holdings)

# Show a preview
df.head()

# 💾 Save to your OneDrive folder (Mac)
today = datetime.date.today().strftime("%Y-%m-%d")

# Replace with your actual path to OneDrive folder
save_path = f"/Users/pranjal/Library/CloudStorage/OneDrive-Personal/Portfolio/holdings_{today}.csv"

# Create folder if it doesn't exist
os.makedirs(os.path.dirname(save_path), exist_ok=True)

df.to_csv(save_path, index=False)
print(f"✅ File saved at: {save_path}")

orders = kite.user_profile()
df2 = pd.DataFrame(orders)

# Show a preview
df2.head()